// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using SurveyBlazorApp.Models.Enums;

#nullable disable

namespace SurveyBlazorApp.Models
{
    public partial class Question
    {
        public Question()
        {
            SurveyResponses = new HashSet<SurveyResponse>();
        }

        [Key]
        public int QuestionId { get; set; }
        [Required]
        [StringLength(255)]
        public string Title { get; set; }
        public QuestionTypes QuestionType { get; set; }
        public string Options { get; set; }
        [Required]
        public bool IsRequired { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }

        [InverseProperty(nameof(SurveyResponse.Question))]
        public virtual ICollection<SurveyResponse> SurveyResponses { get; set; }
    }
}