// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace SurveyBlazorApp.Models
{
    public partial class SurveyResponse
    {
        [Key]
        public int SurveyResponseId { get; set; }
        public int QuestionId { get; set; }
        public string Value { get; set; }
        public int OrderId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }

        [ForeignKey(nameof(QuestionId))]
        [InverseProperty("SurveyResponses")]
        public virtual Question Question { get; set; }
    }
}